name             'workspace'
maintainer       'Jay Flowers'
maintainer_email 'jay.flowers@gmail.com'
description      'Installs/Configures workspace'
long_description 'Installs and configures a workspace for this project'
version          '1.0.0'

depends 'chef_commons'
depends 'virtualbox'
depends 'atom-organism'
depends 'darwin'
depends 'ark'
