name             'taneleer'
maintainer       'Someone'
maintainer_email 'jay.flowers@gmail.com'
description      'Installs/Configures test_mud3 servers'
long_description 'Installs and configures the servers this project produces'
version          '1.0.0'
